/**
 * File-backed store for sweep records.
 *
 * Each sweep lands at `reports/sweeps/<sweepId>.json`. The directory is
 * created lazily on first save. Sweep IDs are sortable timestamps
 * (`sweep-2026-05-24T19-50-23-456Z`) so `ls -1` is chronological.
 *
 * Why file-backed (not in-memory like triage-store / eval-store):
 *  - Sweeps are expensive (~3 min for a 6-point threshold sweep) — losing
 *    them on process restart would be painful.
 *  - The history table on /sweep is more useful with persisted entries.
 *  - JSON files are inspectable, diffable, and grep-able by humans.
 *
 * Storage is full-fidelity: each run keeps its complete EvalReport (per-
 * ticket trace included), so the UI can drill into specific tickets across
 * thresholds. File size is a few MB per sweep — fine at this scale.
 */
import { mkdir, readFile, readdir, writeFile, unlink, stat } from "node:fs/promises";
import { join, resolve } from "node:path";
import type { StoredSweep } from "@/lib/eval/sweep";

const SWEEP_DIR = "reports/sweeps";

function sweepDir(): string {
  return resolve(process.cwd(), SWEEP_DIR);
}

function sweepPath(sweepId: string): string {
  // Defensive: sweep IDs are generated by us, but reject anything that
  // looks like a path-escape just in case.
  if (sweepId.includes("/") || sweepId.includes("..")) {
    throw new Error(`invalid sweep id: ${sweepId}`);
  }
  return join(sweepDir(), `${sweepId}.json`);
}

export async function saveSweep(sweep: StoredSweep): Promise<string> {
  const dir = sweepDir();
  await mkdir(dir, { recursive: true });
  const path = sweepPath(sweep.sweepId);
  await writeFile(path, JSON.stringify(sweep, null, 2), "utf8");
  return path;
}

export async function getSweep(sweepId: string): Promise<StoredSweep | null> {
  try {
    const raw = await readFile(sweepPath(sweepId), "utf8");
    return JSON.parse(raw) as StoredSweep;
  } catch (err: unknown) {
    if ((err as NodeJS.ErrnoException).code === "ENOENT") return null;
    throw err;
  }
}

export async function deleteSweep(sweepId: string): Promise<boolean> {
  try {
    await unlink(sweepPath(sweepId));
    return true;
  } catch (err: unknown) {
    if ((err as NodeJS.ErrnoException).code === "ENOENT") return false;
    throw err;
  }
}

/**
 * Lightweight "metadata only" view of a stored sweep — what the history
 * table needs. Stripping out the per-ticket data here keeps the list
 * payload small even when we have many sweeps stored.
 */
export interface SweepMetadata {
  sweepId: string;
  runAt: string;
  description?: string;
  parameter: StoredSweep["parameter"];
  values: number[];
  options: StoredSweep["options"];
  best: StoredSweep["best"];
  totalDurationMs: number;
  /** Number of completed runs (may be < values.length if some failed). */
  runCount: number;
}

function toMetadata(sweep: StoredSweep): SweepMetadata {
  return {
    sweepId: sweep.sweepId,
    runAt: sweep.runAt,
    description: sweep.description,
    parameter: sweep.parameter,
    values: sweep.values,
    options: sweep.options,
    best: sweep.best,
    totalDurationMs: sweep.totalDurationMs,
    runCount: sweep.runs.length,
  };
}

export async function listSweeps(): Promise<SweepMetadata[]> {
  let entries: string[];
  try {
    entries = await readdir(sweepDir());
  } catch (err: unknown) {
    if ((err as NodeJS.ErrnoException).code === "ENOENT") return [];
    throw err;
  }

  const files = entries.filter((e) => e.endsWith(".json"));
  const sweeps = await Promise.all(
    files.map(async (file) => {
      try {
        const raw = await readFile(join(sweepDir(), file), "utf8");
        const sweep = JSON.parse(raw) as StoredSweep;
        return toMetadata(sweep);
      } catch {
        // Skip corrupt files rather than failing the whole listing.
        return null;
      }
    }),
  );

  return sweeps
    .filter((s): s is SweepMetadata => s !== null)
    .sort((a, b) => b.runAt.localeCompare(a.runAt)); // newest first
}

/** Convenience for the API layer — total bytes on disk for the index card. */
export async function sweepStoreSize(): Promise<{ count: number; bytes: number }> {
  try {
    const entries = await readdir(sweepDir());
    let bytes = 0;
    let count = 0;
    for (const e of entries) {
      if (!e.endsWith(".json")) continue;
      const st = await stat(join(sweepDir(), e));
      bytes += st.size;
      count += 1;
    }
    return { count, bytes };
  } catch (err: unknown) {
    if ((err as NodeJS.ErrnoException).code === "ENOENT") return { count: 0, bytes: 0 };
    throw err;
  }
}
